import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="en">
    <body className={inter.className}>
      <main className="min-w-full h-screen flex justify-center items-center">
        {children}
        <section className="w-2/3 h-screen bg-slate-500"></section>
      </main>
    </body>
  </html>
);

export default RootLayout;
